### ISSUE TITLE
Dev Report "ERROR: expected the file `src/RegNeuralDE.jl` to exist for package `RegNeuralDE` at `/tmp/....`

### ISSUE THREAD

**Issue by linguo4** [avik-pal/RegNeuralDE.jl#98]
Hi, when I tried to install the package, it reports error below.
![image](https://user-images.githubusercontent.com/67442207/189244470-40ab06e2-c243-41ef-90ed-a071afcc1985.png)

Is it the issue from Julia version?
Thank you!

**Comment by avik-pal** [comment]
No, this is a messup I did while renaming the package. I will push a fix by tomorrow. (it is just renaming RegNeuralODE.jl -> RegNeuralDE.jl)

**Comment by avik-pal** [comment]
Should be fixed now

**Comment by linguo4** [comment]
> Should be fixed now
It works. Thank you!
